# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'


target 'TPN_Cocos_Demo-mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    # Pods for TPN_Cocos_Demo-mobile
  pod 'TPNiOS','6.4.76'
  pod 'TPNMaioSDKAdapter','6.4.76'
  pod 'TPNStartAppSDKAdapter','6.4.76'
  pod 'TPNNendSDKAdapter','6.4.76'
  pod 'TPNVungleSDKAdapter','6.4.76'
  pod 'TPNUnityAdsSDKAdapter','6.4.76'
  pod 'TPNIronSourceSDKAdapter','6.4.76'
  pod 'TPNTapjoySDKAdapter','6.4.76'
  pod 'TPNBigoSDKAdapter','6.4.76'
  pod 'TPNAdColonySDKAdapter','6.4.76'
  pod 'TPNPubNativeSDKAdapter','6.4.76'
  pod 'TPNSmaatoSDKAdapter','6.4.76'
  pod 'TPNPangleSDKAdapter','6.4.76'
  pod 'TPNKidozSDKAdapter','6.4.76'
  pod 'TPNAdmobSDKAdapter','6.4.76'
  pod 'TPNInmobiSDKAdapter','6.4.76'
  pod 'TPNApplovinSDKAdapter','6.4.76'
  pod 'TPNMintegralSDKAdapter','6.4.76'
  pod 'TPNChartboostSDKAdapter','6.4.76'
  pod 'TPNYandexSDKAdapter','6.4.76'
  pod 'TPNFyberSDKAdapter','6.4.76'
  pod 'TPNOgurySDKAdapter','6.4.76'
  pod 'TPNBaiduSDKAdapter','6.4.76.1'
  pod 'TPNKuaiShouSDKAdapter','6.4.76'
  pod 'TPNGDTSDKAdapter','6.4.76'
  pod 'TPNDebugUISDK'
  
  pod 'Masonry'

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
         end
    end
  end
end
